version: '3'
services:
  list:
    build:
      context: .
      args:
        SRV_NAME: list
    image: pltvs/todo-list
    container_name: todo-list
    entrypoint: /go/bin/list
    depends_on:
      - db
      - users
    links:
      - db
      - users
    ports:
      - "50001:8080"

  users:
    build:
      context: .
      args:
        SRV_NAME: users
    image: pltvs/todo-users
    container_name: todo-users
    entrypoint: /go/bin/users
    depends_on:
      - db
      - notifier
    links:
      - db
      - notifier
    ports:
      - "50000:8080"

  notifier:
    build:
      context: .
      args:
        SRV_NAME: notifier
    image: pltvs/todo-notifier
    container_name: todo-notifier
    entrypoint: /go/bin/notifier
    ports:
      - "50002:8080"

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    image: pltvs/todo-web
    container_name: todo-web
    depends_on:
      - db
      - list
      - users
    links:
      - db
      - list
      - users
    ports:
      - "3000:8080"

  db:
    image: mongo:3.3
    container_name: todo-db
    logging:
      driver: none
